### ISSUE TITLE
Unable to Recreate Main.rar

### ISSUE THREAD

**Issue by YaaseenM** [hoppas0/ImgSearch#4]
Since the addition the requirements.txt, it helped download all dependencies that are required for the project. As a result, it allows the program to open the window prompt normally. However, after clicking the automatically download button, the program would crash. The image below is the result of the crash
![ProgramIssue](https://github.com/hoppas0/ImgSearch/assets/92874301/bb3390a1-fd12-4865-896e-3f8df41900fd)

Text version of the image:
Unhandled exception in script

Failed to execute script 'main' due to unhandled exception:
'NoneType' object has no attribute 'short_remaining'

Traceback (most recent call last):
  File "main.py", line 249, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "main.py", line 230, in run
AttributeError: 'NoneType' object has no attribute 'short_remaining'

Additionally to the problem, some files are missing from the auto-py-to-exe result.
Missing folders:
cchardet
frozenlist
numpy
psutil

Missing files:
_elementtree
All files containing api-ms-win
libopenblas64__v0.3.21-gcc_10_3_0.dll
ucrtbase.dll

**Comment by hoppas0** [comment]
Sorry, the missing files and folders are due to my different packaging environment and development environment. And I've also updated the requirements .txt, and now you should be able to create a Main.rar like mine.

Regarding the question "'NoneType' object has no attribute 'short_remaining'", I think this is caused by network problems.
This error message indicates that the correct resp is not obtained on line 229 of the main.py.This means that the ImgSearch function is not running correctly.
![屏幕截图 2023-08-26 213516](https://github.com/hoppas0/ImgSearch/assets/89581024/18ffc10b-bfd0-465c-9067-def55c2ef867)
I suggest you run the ImgSearch.py separately (of course, before you need to change the filename and apikey of 10 and 11 lines, and also uncomment 21 lines).
![屏幕截图 2023-08-26 215426](https://github.com/hoppas0/ImgSearch/assets/89581024/76af4530-b332-4b7c-af55-a1dba32f0f7f)
If you don't see something like the image below, it's really a network issue. You can troubleshoot network issues by using a proxy.
![image](https://github.com/hoppas0/ImgSearch/assets/89581024/d5ca3c8b-c8a3-46a6-bd9f-be372574bea0)

Of course, if what I said above is not correct or you have other questions, please be sure to let me know.

**Comment by hoppas0** [comment]
I found the reason for this problem. This problem occurred because I did not pass the apikey in time, which caused the subsequent query to fail, so the returned result was empty.
Now I pass the apikey in line 221 of main.py, and my test results are fine.
![image](https://github.com/hoppas0/ImgSearch/assets/89581024/2f868df4-69c3-4bae-82a0-448bd8aad14e)

**Comment by YaaseenM** [comment]
What IDE are you using? I am using Pycharm and I am having trouble installing cchardet. It says I need Visual Studio C++. I tried running ImgSearch.py but it still failed. I edited lines 10 and 11, and I also uncomment line 21. I am currently trying to find a proxy to use to test the ImgSearch.py.

**Comment by hoppas0** [comment]
The IDE I'm using is PyCharm. And I didn't have any issues installing cchardet with PyCharm.
![屏幕截图 2023-08-28 213431](https://github.com/hoppas0/ImgSearch/assets/89581024/340b5fbf-4bad-4e1d-a9de-171887e0a917)

I'm not having problems here, probably because I've installed Visual Studio before.Maybe downloading this (https://visualstudio.microsoft.com/visual-cpp-build-tools/) will solve your problem

I saw from the Internet that someone solved this problem after installing Cython, maybe you can try this method as well.

**Comment by hoppas0** [comment]
Are you having trouble with v2.1.0 in Releases? If you don't encounter problems, it's proof that there are no problems with your network.
